-- AUTO-GENERATED by scripts/gen-seed.mjs from nextjs-sample/data/mock. Safe to re-run (idempotent where keyed).

-- store categories
insert into store_categories (id, name, old_import_id) values (3, 'Παιδικά / Βρεφικά / Παιχνίδια', 3) on conflict (id) do update set name = excluded.name;
insert into store_categories (id, name, old_import_id) values (4, 'Αθλητικά', 4) on conflict (id) do update set name = excluded.name;
insert into store_categories (id, name, old_import_id) values (5, 'Ένδυση / Υπόδηση', 5) on conflict (id) do update set name = excluded.name;
insert into store_categories (id, name, old_import_id) values (6, 'Βιβλιοπωλεία', 6) on conflict (id) do update set name = excluded.name;
insert into store_categories (id, name, old_import_id) values (7, 'Ηλεκτρονικά', 7) on conflict (id) do update set name = excluded.name;
insert into store_categories (id, name, old_import_id) values (8, 'Ψυχαγωγία / Εστιατόρια', 8) on conflict (id) do update set name = excluded.name;
insert into store_categories (id, name, old_import_id) values (12, 'Ζαχαροπλαστεία', 12) on conflict (id) do update set name = excluded.name;
insert into store_categories (id, name, old_import_id) values (13, 'Σπίτι / Διακόσμηση', 13) on conflict (id) do update set name = excluded.name;
insert into store_categories (id, name, old_import_id) values (14, 'Ταξίδια & Τσάντες', 14) on conflict (id) do update set name = excluded.name;
insert into store_categories (id, name, old_import_id) values (15, 'Υπηρεσίες', 15) on conflict (id) do update set name = excluded.name;
insert into store_categories (id, name, old_import_id) values (16, 'Οπτικά', 16) on conflict (id) do update set name = excluded.name;
insert into store_categories (id, name, old_import_id) values (19, 'Είδη σπιτιού', 19) on conflict (id) do update set name = excluded.name;
select setval('store_categories_id_seq', (select max(id) from store_categories));

-- partner stores
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Paperworks Philippides', 6, '22879222', null, 'Εξαιρούνται τα οπτικά είδη', 'stores/store-1.jpg', 1) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('ΑΘΛΟΚΙΝΗΣΗ', 4, '25822414', null, null, 'stores/store-2.jpg', 2) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Okaidi', 3, '23740835', null, 'Παιδικά είδη ένδυσης υπόδησης', 'stores/store-4.jpg', 4) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Allforkids', 3, '25384844', 'https://www.allforkidsshop.com/', 'Παιδικά Είδη Υπόδησης', 'stores/store-5.jpg', 5) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('De Ninos', 3, '25581896', 'https://www.facebook.com/DeNinosCy', 'Παιδικά είδη', 'stores/store-6.jpg', 6) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Engino', 3, '25821960', 'www.enginotoys.com', 'Online — χρησιμοποίησε τον κωδικό «keanitakidsclub» στο ταμείο', 'stores/store-9.jpg', 9) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Ηλεκτρονικό κατάστημα (Inventor & QBoidz)')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('KBV', 3, '24665202', null, 'Παιδικά Είδη Ένδυσης', 'stores/store-10.jpg', 10) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (20, 'Πλήρες πακέτο βάπτισης')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Mikellides Sports', 4, '25371918', 'www.mikellides-sports.com', null, 'stores/store-12.jpg', 12) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Παιδικά'),(10, 'Γυναικεία & Ανδρικά')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('M. Pamboris Sports', 4, '24651551', 'www.pamboris@cytanet.com.cy', null, 'stores/store-13.jpg', 13) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Όλα τα είδη'),(10, 'Nike')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('AWOL', 4, '22106367', null, null, 'stores/store-14.jpg', 14) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Biker Bike shop', 4, null, null, null, 'stores/store-15.jpg', 15) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (20, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Υδάτινος Κόσμος — Είδη Κολύμβησης', 4, null, null, null, 'stores/store-16.jpg', 16) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (20, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('No Name', 5, null, null, null, 'stores/store-17.jpg', 17) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Camel Active', 5, null, null, null, 'stores/store-18.jpg', 18) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Hyper', 5, null, null, null, 'stores/store-19.jpg', 19) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Emporio Sportivo', 5, null, null, null, 'stores/store-20.jpg', 20) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Parga Bookstore', 6, null, null, null, 'stores/store-21.jpg', 21) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Ηλεκτρονικό κατάστημα')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Επιλογή', 6, null, null, null, 'stores/store-22.jpg', 22) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (20, 'Χαρτικά & σχολικά είδη')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('ΒΙΒΛΙΟΧΩΡΑ', 6, null, null, null, 'stores/store-24.jpg', 24) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (35, 'Είδη βιβλιοπωλείου'),(22, 'Παιδικά βιβλία, χαρτικά'),(10, 'Εκπαιδευτικά παιχνίδια (καθαρή τιμή)')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Bricks 4 Kids Club', 8, null, null, null, 'stores/store-25.jpg', 25) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Dine in & Play / μαθήματα LEGO Robotics')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('PUZZLES Children Center', 8, null, null, null, 'stores/store-26.jpg', 26) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Είσοδος')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('PLAY 4 ALL', 8, null, null, null, 'stores/store-28.jpg', 28) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Μόνο Bowling & Jungle')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('MASTER LAND', 8, null, null, null, 'stores/store-29.jpg', 29) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (20, 'Είσοδος')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('PAFOS LOUNA PARK', 8, null, null, null, 'stores/store-30.jpg', 30) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (20, 'Σύνολο φαγητού / ποτού (εξαιρούνται τα πάρτι)')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('PIZZA EXPRESS', 8, null, null, null, 'stores/store-31.jpg', 31) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (10, 'Δευ–Κυρ στο κατάστημα (μεσημέρι ή βράδυ)')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('GARDEN CENTER', 19, null, null, null, 'stores/store-32.jpg', 32) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Όλα τα φυτά & κατασκευές κήπου'),(10, 'Διακοσμήσεις γάμου / βάπτισης')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('English, Robotics & Computer Lessons', 15, null, null, null, 'stores/store-33.jpg', 33) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (20, 'Δίδακτρα (ένα ακαδημαϊκό έτος)')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Costas Theodorou Ltd', 14, null, null, null, 'stores/store-34.jpg', 34) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('KYRANTO', 16, null, null, null, 'stores/store-35.jpg', 35) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (20, 'Σκελετοί οράσεως & γυαλιά ηλίου'),(15, 'Oakley & Maui Jim')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('THEOFANIDES EYE WORD', 16, null, null, null, 'stores/store-36.jpg', 36) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (30, 'Σκελετοί οράσεως & γυαλιά ηλίου')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('THEMA collection', 5, null, null, null, 'stores/store-38.jpg', 38) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Trapped In Limassol Escape Rooms', 8, null, null, null, 'stores/store-39.jpg', 39) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (20, '1 ώρα Escape Room'),(10, 'Πάρτι γενεθλίων')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Boobooideas by I.S.', 15, null, null, null, 'stores/store-42.jpg', 42) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Online παραγγελία μέσω Instagram')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('E.C. NetTech Solutions Ltd', 7, null, null, null, 'stores/store-43.jpg', 43) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Αφαίρεση ιών, αναλώσιμα & επισκευές')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Fouskotopia Bouncy Castle', 15, null, null, null, 'stores/store-44.jpg', 44) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (20, 'Κάθε φουσκωτό κάστρο')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Famous Sports', 4, null, null, null, 'stores/store-45.jpg', 45) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Paradox Museum Limassol', 8, null, null, null, 'stores/store-46.jpg', 46) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (30, 'Είσοδος')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('Marzano', 8, null, null, null, 'stores/store-47.jpg', 47) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (10, 'Έκπτωση')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('LE TRONE NOIR', 3, null, null, null, 'stores/store-48.jpg', 48) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Πλήρες πακέτο βάπτισης'),(10, 'Ρούχα / παπούτσια')) as d(v, d);
with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values ('SAKURA by Loizos Loizou / Flower Shop', 13, null, null, null, 'stores/store-49.jpg', 49) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values (15, 'Στο κατάστημα'),(15, 'Online — κωδικός KEAN15')) as d(v, d);

-- products
insert into products (name, category, tagline, description, image_url, accent_color, bg_color, serving_size, highlights, ingredients, nutrition, sort_order, old_import_id) values ('Πορτοκάλι', 'juice', '20% φυσικός χυμός + βιταμίνη C', 'Φτιαγμένο από τα πιο νόστιμα πορτοκάλια, με 20% φυσικό χυμό και έξτρα βιταμίνη C. Το Keanita Πορτοκάλι είναι φτιαγμένο ειδικά για παιδιά — θρεπτικό, τονωτικό και γεμάτο τις γεύσεις που αγαπούν.', 'products/juice-orange-new.png', '#F5A623', '#FFF6E8', 'ανά 100ml', array['20% Φυσικός χυμός','Έξτρα βιταμίνη C','Χωρίς συντηρητικά']::text[], array['Νερό','20% Χυμός πορτοκαλιού από συμπυκνωμένο','Ζάχαρη','Φυσικό άρωμα πορτοκαλιού','Βιταμίνη C (ασκορβικό οξύ)']::text[], '[{"label":"Ενέργεια","value":"184kJ / 43kcal"},{"label":"Λιπαρά","value":"0g"},{"label":"— εκ των οποίων κορεσμένα","value":"0g"},{"label":"Υδατάνθρακες","value":"10.8g"},{"label":"Σάκχαρα","value":"10.8g"},{"label":"Πρωτεΐνη","value":"0g"},{"label":"Αλάτι","value":"0g"},{"label":"Βιταμίνη C","value":"12mg"}]', 0, 1);
insert into products (name, category, tagline, description, image_url, accent_color, bg_color, serving_size, highlights, ingredients, nutrition, sort_order, old_import_id) values ('Μάνγκο', 'juice', 'Τροπική απόλαυση μάνγκο', 'Το μάνγκο — ο «βασιλιάς των φρούτων» — μέσα σε ένα παιδικό κουτάκι. Πλούσιο σε φυτικές ίνες, χωρίς συντηρητικά και με έξτρα βιταμίνη C, το Keanita Μάνγκο είναι ο τέλειος ξεδιψαστής.', 'products/juice-mango.png', '#6BBF6A', '#EEFBEE', 'ανά 100ml', array['20% Φυσικός χυμός','Πλούσιο σε φυτικές ίνες','Έξτρα βιταμίνη C']::text[], array['Νερό','20% Πουρές μάνγκο από συμπυκνωμένο','Ζάχαρη','Φυσικό άρωμα μάνγκο','Βιταμίνη C (ασκορβικό οξύ)']::text[], '[{"label":"Ενέργεια","value":"221kJ / 52kcal"},{"label":"Λιπαρά","value":"0g"},{"label":"— εκ των οποίων κορεσμένα","value":"0g"},{"label":"Υδατάνθρακες","value":"12.8g"},{"label":"Σάκχαρα","value":"12.8g"},{"label":"Πρωτεΐνη","value":"0g"},{"label":"Αλάτι","value":"0g"},{"label":"Βιταμίνη C","value":"12mg"}]', 1, 2);
insert into products (name, category, tagline, description, image_url, accent_color, bg_color, serving_size, highlights, ingredients, nutrition, sort_order, old_import_id) values ('Frumix', 'juice', 'Ένα μείγμα 5 φρούτων', 'Μια φρουτοσαλάτα μέσα σε ένα μικρό κουτάκι! Με έξτρα βιταμίνη C, χωρίς συντηρητικά, περισσότερο φυσικό χυμό και τη γεύση 5 φρούτων — μήλο, πορτοκάλι, ανανάς, ροδάκινο και μάνγκο.', 'products/juice-frumix.png', '#5DADE2', '#EDF7FD', 'ανά 100ml', array['Μείγμα 5 φρούτων','Έξτρα βιταμίνη C','Χωρίς συντηρητικά']::text[], array['Νερό','Χυμός μήλου από συμπυκνωμένο','Χυμός πορτοκαλιού από συμπυκνωμένο','Χυμός ανανά από συμπυκνωμένο','Πουρές ροδάκινου','Πουρές μάνγκο','Ζάχαρη','Βιταμίνη C (ασκορβικό οξύ)']::text[], '[{"label":"Ενέργεια","value":"191kJ / 45kcal"},{"label":"Λιπαρά","value":"0g"},{"label":"— εκ των οποίων κορεσμένα","value":"0g"},{"label":"Υδατάνθρακες","value":"11.3g"},{"label":"Σάκχαρα","value":"11.3g"},{"label":"Πρωτεΐνη","value":"0g"},{"label":"Αλάτι","value":"0g"},{"label":"Βιταμίνη C","value":"12mg"}]', 2, 3);
insert into products (name, category, tagline, description, image_url, accent_color, bg_color, serving_size, highlights, ingredients, nutrition, sort_order, old_import_id) values ('Πορτοκάλι Στέβια', 'juice', 'Λιγότερη ζάχαρη, ίδια γεύση', 'Η αυθεντική γεύση Keanita Πορτοκάλι με 20% φυσικό χυμό και έξτρα βιταμίνη C — γλυκαμένη φυσικά με εκχύλισμα φύλλων στέβιας, χωρίς προσθήκη ζάχαρης.', 'products/juice-stevia.png', '#6BBF6A', '#EEFBEE', 'ανά 100ml', array['Χωρίς προσθήκη ζάχαρης','Γλυκαμένο με στέβια','Έξτρα βιταμίνη C']::text[], array['Νερό','20% Χυμός πορτοκαλιού από συμπυκνωμένο','Φυσικό άρωμα πορτοκαλιού','Γλυκοζίτες στεβιόλης (από φύλλα στέβιας)','Βιταμίνη C (ασκορβικό οξύ)']::text[], '[{"label":"Ενέργεια","value":"100kJ / 24kcal"},{"label":"Λιπαρά","value":"0g"},{"label":"— εκ των οποίων κορεσμένα","value":"0g"},{"label":"Υδατάνθρακες","value":"6.0g"},{"label":"Σάκχαρα","value":"5.8g"},{"label":"Πρωτεΐνη","value":"0g"},{"label":"Αλάτι","value":"0g"},{"label":"Βιταμίνη C","value":"12mg"}]', 3, 4);
insert into products (name, category, tagline, description, image_url, accent_color, bg_color, serving_size, highlights, ingredients, nutrition, sort_order, old_import_id) values ('Γιαούρτι Φράουλα', 'yogurt', 'Βελούδινο με αληθινή φράουλα', 'Νόστιμο, φραουλένιο και εμπλουτισμένο με ασβέστιο και βιταμίνη D. Το τέλειο σνακ για παιδιά — για πρωινό, απογευματινή τόνωση, ή ακόμη και για πάρτι γενεθλίων!', 'products/yogurt-strawberry.png', '#E84D3D', '#FFF0EE', 'ανά 100g', array['Πλούσιο σε ασβέστιο','Πηγή βιταμίνης D','Αληθινή φράουλα']::text[], array['Παστεριωμένο αγελαδινό γάλα','Κομμάτια φράουλας (8%)','Ζάχαρη','Αποβουτυρωμένο γάλα σε σκόνη','Τρούφα σοκολάτας','Καλλιέργειες γιαουρτιού','Βιταμίνη D']::text[], '[{"label":"Ενέργεια","value":"471kJ / 112kcal"},{"label":"Λιπαρά","value":"3.4g"},{"label":"— εκ των οποίων κορεσμένα","value":"2.1g"},{"label":"Υδατάνθρακες","value":"16g"},{"label":"— εκ των οποίων σάκχαρα","value":"12g"},{"label":"Πρωτεΐνη","value":"4.3g"},{"label":"Αλάτι","value":"0.12g"},{"label":"Ασβέστιο","value":"140mg (26% NRV*)"},{"label":"Βιταμίνη D","value":"0.7µg (20% NRV*)"}]', 4, 5);

-- characters
insert into characters (id, slug, name, tagline, description, best_friend, power, favorite_juice, image_url, accent_color, bg_color, sort_order) values (1, 'keanita', 'KEANITA', 'Η εξερευνήτρια του χυμού', 'Η KEANITA είναι ένα ξέγνοιαστο κορίτσι που αγαπά τη φύση, συναισθηματική και συμπονετική. Είναι δραστήρια και της αρέσουν η γυμναστική και η κηπουρική γιατί λατρεύει τη φύση! Ταξιδεύει στον κόσμο των υπολογιστών με χαρά και περιέργεια σαν εξερευνήτρια. Στο σπίτι την υποδέχονται η οικογένειά της και ο απίστευτα αξιολάτρευτος σκύλος ΤΟΝΙ!', 'Ο Βίκτωρας (αλληλοσυμπληρώνονται)', null, 'Πορτοκάλι', 'characters/character-1.png', '#1E9A3D', '#DCF5DC', 0) on conflict (slug) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description;
insert into characters (id, slug, name, tagline, description, best_friend, power, favorite_juice, image_url, accent_color, bg_color, sort_order) values (2, 'viktoras', 'ΒΙΚΤΩΡΑΣ', 'Ο ιδιοφυής εξερευνητής', 'Ο Βίκτωρας είναι ένα ήσυχο αγόρι που περνά τον χρόνο του διαβάζοντας. Είναι εξαιρετικά έξυπνος — το IQ του ξεπερνά το 300. Γνωρίζει κάθε λεπτομέρεια από τις τελευταίες παγκόσμιες ειδήσεις, και οτιδήποτε έχει να κάνει με το πώς μπορεί κανείς να επιβιώσει κάτω από οποιεσδήποτε συνθήκες. Αν και ντροπαλός, είναι υπεύθυνος στον ρόλο του και πολύ πρακτικός. Εξοπλισμένος με έντονη ερευνητική διαίσθηση και gadget υψηλής τεχνολογίας που τον βοηθούν στις αποστολές του.', 'Η KEANITA (τη θαυμάζει και είναι κρυφά ερωτευμένος)', null, 'Μήλο', 'characters/character-2.png', '#E11915', '#FFD9D4', 1) on conflict (slug) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description;
insert into characters (id, slug, name, tagline, description, best_friend, power, favorite_juice, image_url, accent_color, bg_color, sort_order) values (3, 'magkas', 'ΜΑΓΚΑΣ', 'Ο κύριος του καιρού', 'Ο Μάγκας είναι ένας απόμακρος και σκληρός χαρακτήρας, με προστατευτική όμως διάθεση. Δεν του αρέσει όταν κάποιος αμφισβητεί τις ηγετικές του ικανότητες, και λατρεύει όταν οι συμβουλές και οι απόψεις του ακούγονται χωρίς δισταγμό. Έχει την ικανότητα να μετρά τα πάντα με το καλαμάκι-κεφάλι του.', 'Ο Λέφης (τον νιώθει σαν φύλακα άγγελό του)', 'Μπορεί να αλλάζει τις καιρικές συνθήκες και να δημιουργεί τυφώνες, σεισμούς, λιακάδα, καταιγίδες κ.λπ. όποτε το επιλέξει', 'Frumix', 'characters/character-3.png', '#1E9A3D', '#DCF5DC', 2) on conflict (slug) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description;
insert into characters (id, slug, name, tagline, description, best_friend, power, favorite_juice, image_url, accent_color, bg_color, sort_order) values (4, 'lefis', 'ΛΕΦΗΣ', 'Ο μεταμορφωτής', 'Ο Λέφης είναι γεμάτος γοητεία και χαμόγελα και πιστεύει ότι ακόμη και οι κακοί έχουν κάποια ευαισθησία, γι'' αυτό προσπαθεί να οδηγήσει τους πάντες στον σωστό δρόμο χωρίς να χρησιμοποιεί τις δυνάμεις του. Του αρέσουν τα όμορφα και στιλάτα κορίτσια και οτιδήποτε χνουδωτό και απαλό. Δεν μπορεί να προφέρει το γράμμα Σ (μιλά με Θ — π.χ. «θέλειθ να χορέψουμε;»).', 'Ο Μάγκας (φαίνεται να ξέρει πολλά και του έχει σώσει τη ζωή πολλές φορές)', 'Μπορεί να πάρει όποια μορφή θέλει', 'Μάνγκο', 'characters/character-4.png', '#E11915', '#FFD9D4', 3) on conflict (slug) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description;
select setval('characters_id_seq', (select max(id) from characters));

-- events (sample, published)
insert into events (type, title, description, date, time_label, location, image_url, accent_color, bg_color, status, sort_order, old_import_id) values ('event', 'Ημέρα διασκέδασης στο Riverland', 'Εργαστήρι κηπουρικής, μάθημα μαγειρικής & δραστηριότητες φάρμας για παιδιά 5-11!', '2026-04-15', '11:00 - 13:00', 'Riverland Bio Farm', 'events/event-riverland.jpg', '#E84D3D', '#FFF0EE', 'published', 0, 1);
insert into events (type, title, description, date, time_label, location, image_url, accent_color, bg_color, status, sort_order, old_import_id) values ('event', 'Πάρτι γενεθλίων Keanita', 'Έλα στη μεγάλη γιορτή γενεθλίων της Keanita με παιχνίδια και δώρα!', '2026-05-01', '15:00 - 20:00', 'Εργοστάσιο KEAN, Λεμεσός', 'events/event-birthday.jpg', '#F5A623', '#FFF6E8', 'published', 1, 3);
insert into events (type, title, description, date, time_label, location, image_url, accent_color, bg_color, status, sort_order, old_import_id) values ('announcement', 'Πασχαλινός διαγωνισμός', 'Κέρδισε ένα πασχαλινό σετ Keanita με λιχουδιές και εκπλήξεις!', '2026-05-10', 'Όλη μέρα', 'Διαδικτυακή εκδήλωση', 'events/event-easter.jpg', '#9B7FD4', '#F4F0FA', 'published', 2, 4);
insert into events (type, title, description, date, time_label, location, image_url, accent_color, bg_color, status, sort_order, old_import_id) values ('announcement', 'Παρουσίαση του Keanita Avatar', 'Γνώρισε το νέο μας avatar που προωθεί τη θετική ενέργεια και τον αγώνα κατά του bullying!', '2026-05-18', '12:00', 'Διαδικτυακή εκδήλωση', 'events/event-avatar.jpg', '#5DADE2', '#EDF7FD', 'published', 3, 5);
insert into events (type, title, description, date, time_label, location, image_url, accent_color, bg_color, status, sort_order, old_import_id) values ('seminar', 'Σεμινάριο «Getting Nutty»', 'Μια διασκεδαστική πειραματική ημέρα για τη διατροφή και την υγιεινή ζωή.', '2026-04-22', '11:00 - 13:00', 'Λευκωσία', 'events/event-nutty.jpg', '#6BBF6A', '#EEFBEE', 'published', 4, 2);
insert into events (type, title, description, date, time_label, location, image_url, accent_color, bg_color, status, sort_order, old_import_id) values ('seminar', 'Εργαστήρι υγιεινών συνηθειών', 'Μάθε πώς να χτίζεις υγιεινές καθημερινές συνήθειες με παιχνίδια και διασκεδαστικά μαθήματα.', '2026-06-05', '10:00 - 12:00', 'Λεμεσός', 'events/event-nutty.jpg', '#6BBF6A', '#EEFBEE', 'published', 5, 6);

-- home sliders
insert into home_sliders (title, subtitle, image_url, accent_color, bg_color, sort_order) values ('Καλώς ήρθες στο
Keanita Kids Club!', 'Διασκέδαση, χυμοί & περιπέτειες σε περιμένουν', 'sliders/banner.png', '#E84D3D', '#FFF0EE', 0);
insert into home_sliders (title, subtitle, image_url, accent_color, bg_color, sort_order) values ('Ημέρα διασκέδασης
στο Riverland!', 'Εργαστήρια, μαγειρική & διασκέδαση στη φάρμα', 'sliders/event-riverland.jpg', '#E84D3D', '#FFF0EE', 1);
insert into home_sliders (title, subtitle, image_url, accent_color, bg_color, sort_order) values ('Πασχαλινός
διαγωνισμός!', 'Κέρδισε ένα πασχαλινό σετ Keanita', 'sliders/event-easter.jpg', '#9B7FD4', '#F4F0FA', 2);

-- activities
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('puzzle', 'Χρωμοσελίδα ΚΕΑΝΙΤΑ', 'Χρωμοσελίδες', 'activities/drawing-18-image.jpg', 'https://www.evenziademo3.com/media/1195/KEANITA-COLOURINGPAGE-KEANITA-1.pdf', 0, 18);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('puzzle', 'Μαθηματικά με χρώμα', 'Χρωμοσελίδες', 'activities/drawing-19-image.jpg', 'https://www.evenziademo3.com/media/1197/KEANITA-COLOURINGPAGE-maths.pdf', 1, 19);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('puzzle', 'Λαβύρινθος', 'Χρωμοσελίδες', 'activities/drawing-20-image.jpg', 'https://www.evenziademo3.com/media/1201/KEANITA-COLOURINGPAGE-maze2.pdf', 2, 20);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('puzzle', 'Πασχαλινή πεταλούδα', 'Χρωμοσελίδες', 'activities/drawing-17-image.jpg', 'https://www.evenziademo3.com/media/1397/KEANITA-Easter_butterfly.pdf', 3, 17);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('puzzle', 'Γρίφος 1', 'Χρωμοσελίδες', 'activities/drawing-7-image.jpg', 'https://www.evenziademo3.com/media/1419/diagonismos-trapped_1-2.pdf', 4, 7);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('puzzle', 'Γρίφος 2', 'Χρωμοσελίδες', 'activities/drawing-14-image.jpg', 'https://www.evenziademo3.com/media/1421/diagonismos-trapped_1-3.pdf', 5, 14);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('puzzle', 'Γρίφος 3', 'Χρωμοσελίδες', 'activities/drawing-15-image.jpg', 'https://www.evenziademo3.com/media/1423/diagonismos-trapped_1-4.pdf', 6, 15);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('puzzle', 'Γρίφος 4', 'Χρωμοσελίδες', 'activities/drawing-16-image.jpg', 'https://www.evenziademo3.com/media/1425/diagonismos-trapped_1-5.pdf', 7, 16);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('download', 'Back 2 School Δραστηριότητες', 'Δραστηριότητες', 'activities/newsletter-26-image.png', 'https://www.evenziademo3.com/media/1427/Back-to-school2022.pdf', 0, 26);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('download', 'Τα Πάντα για Μένα', 'Δραστηριότητες', 'activities/newsletter-27-image.jpg', 'https://www.evenziademo3.com/media/1429/Black-and-white-all-about-me-back-to-school-worksheet-(1).pdf', 1, 27);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('download', 'Σελιδοδείκτης ΚΕΑΝΙΤΑ', 'Κατασκευές DIY', 'activities/newsletter-28-image.jpg', 'https://www.evenziademo3.com/media/1431/bookmark-keanita.pdf', 2, 28);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('download', 'Σχολικό Πρόγραμμα ΚΕΑΝΙΤΑ', 'Κατασκευές DIY', 'activities/newsletter-29-image.jpg', 'https://www.evenziademo3.com/media/1433/Programma_colour.pdf', 3, 29);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('download', 'Ανοιξιάτικες ΚΕΑΝΙΤΟ-δραστηριότητες', 'Δραστηριότητες', 'activities/newsletter-4-image.jpg', 'https://www.evenziademo3.com/media/1252/Spring_KEANITA2024.pdf', 4, 4);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('download', 'Γιρλάντα Λουλουδιών DIY', 'Κατασκευές DIY', 'activities/newsletter-5-image.jpg', 'https://www.evenziademo3.com/media/1253/MAY_KEANITA_2024.pdf', 5, 5);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('download', 'Παιχνίδι 1980''s Retro', 'Κατασκευές DIY', 'activities/newsletter-11-image.jpg', 'https://www.evenziademo3.com/media/1259/game-retro.pdf', 6, 11);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('download', 'Οικολογικές Δραστηριότητες', 'Δραστηριότητες', 'activities/newsletter-12-image.jpg', 'https://www.evenziademo3.com/media/1258/Eco-KEANITA_conv2024.pdf', 7, 12);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('download', 'Γωνιακοί Σελιδοδείκτες ORIGAMI', 'Κατασκευές DIY', 'activities/newsletter-13-image.jpg', 'https://www.evenziademo3.com/media/1255/bookmark-origami-1.pdf', 8, 13);
insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('download', 'Μαθαίνω Αγγλικά!', 'Δραστηριότητες', 'activities/newsletter-14-image.jpg', 'https://www.evenziademo3.com/media/1257/Alphabet_KEANITA2024.pdf', 9, 14);

-- gifts
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Προσωποποιημένη κάρτα γενεθλίων', 'Μια ψηφιακή κάρτα Keanita με το όνομά σου.', 150, 'digital', '🎂', '#E84D3D', '#FFF0EE', null, false, 0);
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Κινούμενο σήμα προφίλ', 'Ένα λαμπερό σήμα που εμφανίζεται στο προφίλ σου.', 200, 'digital', '⭐', '#F5A623', '#FFF6E8', null, false, 1);
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Εκτυπώσιμο πακέτο δραστηριοτήτων', 'Λαβύρινθοι, ζωγραφική & παζλ για εκτύπωση στο σπίτι.', 250, 'digital', '🧩', '#6BBF6A', '#EEFBEE', null, false, 2);
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Ψηφιακό παραμύθι', 'Ένα παραμύθι περιπέτειας Keanita μέσα στην εφαρμογή.', 300, 'digital', '📖', '#5DADE2', '#EDF7FD', null, false, 3);
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Premium πακέτο ρούχων', 'Ντύσε τον χαρακτήρα σου με 3 νέα σύνολα.', 400, 'digital', '👕', '#9B7FD4', '#F4F0FA', null, false, 4);
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Αποκλειστικό θέμα παιχνιδιού', 'Μια ολοκαίνουργια εμφάνιση για τη Φρουτοτρέλα.', 500, 'digital', '🎮', '#E84D3D', '#FFF0EE', null, false, 5);
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Αυτοκόλλητα Keanita', 'Ένα φύλλο με γυαλιστερά αυτοκόλλητα της μασκότ.', 800, 'physical', '✨', '#F5A623', '#FFF6E8', null, true, 6);
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Βιβλίο ζωγραφικής Keanita', '32 σελίδες φρουτένιας ζωγραφικής διασκέδασης.', 1200, 'physical', '🖍️', '#6BBF6A', '#EEFBEE', null, true, 7);
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Σετ κασετίνας', 'Μια κασετίνα Keanita + γραφική ύλη.', 1800, 'physical', '✏️', '#5DADE2', '#EDF7FD', 0, true, 8);
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Λούτρινη Keanita', 'Μια αγκαλίτσα-μασκότ Keanita από λούτρινο.', 3500, 'physical', '🧸', '#E84D3D', '#FFF0EE', null, true, 9);
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Μπλουζάκι Keanita', 'Ένα απαλό βαμβακερό μπλουζάκι στο μέγεθός σου.', 4000, 'physical', '👕', '#9B7FD4', '#F4F0FA', null, true, 10);
insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values ('Σακίδιο Keanita', 'Το κορυφαίο σακίδιο του Kids Club.', 6000, 'physical', '🎒', '#F5A623', '#FFF6E8', null, true, 11);

-- reward rules
insert into reward_rules (key, label, points, daily_cap, config) values ('daily_login', 'Ημερήσια σύνδεση', 5, null, '{}') on conflict (key) do nothing;
insert into reward_rules (key, label, points, daily_cap, config) values ('streak_bonus', 'Μπόνους σερί', 10, null, '{"tiers":{"3":10,"7":30,"30":100}}') on conflict (key) do nothing;
insert into reward_rules (key, label, points, daily_cap, config) values ('game', 'Φρουτοτρέλα (ανά φρούτο)', 1, 150, '{"completion_bonus":5}') on conflict (key) do nothing;
insert into reward_rules (key, label, points, daily_cap, config) values ('event_rsvp', 'Δήλωση συμμετοχής σε εκδήλωση', 10, null, '{}') on conflict (key) do nothing;
insert into reward_rules (key, label, points, daily_cap, config) values ('profile_complete', 'Συμπλήρωση προφίλ', 50, null, '{}') on conflict (key) do nothing;
insert into reward_rules (key, label, points, daily_cap, config) values ('qr_scan', 'Σκανάρισμα QR προϊόντος', 20, null, '{}') on conflict (key) do nothing;
insert into reward_rules (key, label, points, daily_cap, config) values ('birthday', 'Δώρο γενεθλίων', 50, null, '{}') on conflict (key) do nothing;
insert into reward_rules (key, label, points, daily_cap, config) values ('gift_redeem', 'Εξαργύρωση δώρου', 0, null, '{}') on conflict (key) do nothing;
insert into reward_rules (key, label, points, daily_cap, config) values ('refund', 'Επιστροφή πόντων', 0, null, '{}') on conflict (key) do nothing;
insert into reward_rules (key, label, points, daily_cap, config) values ('manual', 'Χειροκίνητη προσαρμογή', 0, null, '{}') on conflict (key) do nothing;
insert into reward_rules (key, label, points, daily_cap, config) values ('expiry', 'Λήξη πόντων', 0, null, '{}') on conflict (key) do nothing;

-- app settings
insert into app_settings (key, value, description) values ('contact_email', '"keanita@keanltd.com.cy"'::jsonb, 'Email επικοινωνίας') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('contact_phone', '"80007090"'::jsonb, 'Τηλέφωνο επικοινωνίας') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('contact_address', '"Τ.Θ. 50300, 3603, Λεμεσός"'::jsonb, 'Διεύθυνση') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('contact_hours', '"Δευ–Πέμ 10:00–13:00 & 14:00–16:00, Παρ 10:00–13:30"'::jsonb, 'Ώρες λειτουργίας') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('emergency_phone', '"80007090"'::jsonb, 'Αριθμός κουμπιού έκτακτης ανάγκης (αρχική οθόνη)') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('social_facebook', '"https://www.facebook.com/keanita"'::jsonb, 'Facebook') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('social_instagram', '"https://www.instagram.com/keanitaofficial/"'::jsonb, 'Instagram') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('social_youtube', '"https://www.youtube.com/user/keansoftdrinks"'::jsonb, 'YouTube') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('kid_max_age', '11'::jsonb, 'Ηλικία λήξης μέλους Kids Club') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('kid_auto_approve', 'false'::jsonb, 'Αυτόματη έγκριση παιδιών') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('points_expiry_months', '12'::jsonb, 'Μήνες μέχρι τη λήξη πόντων') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('birthday_push_enabled', 'true'::jsonb, 'Αποστολή ευχών γενεθλίων') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('birthday_message', '"Χρόνια πολλά {name}! 🎂 Η Keanita σου εύχεται μια υπέροχη μέρα γεμάτη χυμό και χαμόγελα!"'::jsonb, 'Μήνυμα γενεθλίων ({name} = όνομα παιδιού)') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('birthday_points', '50'::jsonb, 'KP δώρο γενεθλίων') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('birthday_video_url', 'null'::jsonb, 'Βίντεο γενεθλίων') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('intro_video_url', 'null'::jsonb, 'Εισαγωγικό βίντεο') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('event_reminder_days', '2'::jsonb, 'Ημέρες πριν την εκδήλωση για υπενθύμιση') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('membership_tier_label', '"Χρυσό μέλος"'::jsonb, 'Ετικέτα επιπέδου μέλους (προφίλ)') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('home_product_chips', '[{"emoji":"🍊","label":"20% φυσικός χυμός"},{"emoji":"✨","label":"Έξτρα βιταμίνη C"},{"emoji":"🌿","label":"Χωρίς πρόσθετα"}]'::jsonb, 'Chips προϊόντων στην αρχική') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('home_quick_actions', '["rewards","gifts","discounts","products","activities","about"]'::jsonb, 'Ενεργά κουμπιά γρήγορης πρόσβασης') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('min_app_version', '"1.0.0"'::jsonb, 'Ελάχιστη έκδοση εφαρμογής (force update)') on conflict (key) do nothing;
insert into app_settings (key, value, description) values ('maintenance_mode', 'false'::jsonb, 'Λειτουργία συντήρησης') on conflict (key) do nothing;

-- pages
insert into pages (slug, title, body_md) values ('terms', 'Όροι & Κανονισμοί', '# Όροι και Κανονισμοί

Το application ΚΕΑΝΙΤΑ είναι διαθέσιμο για πρόσβαση και χρήση και δεν απαιτεί εγγραφή.

Σε περίπτωση που επιθυμείτε τα παιδιά σας να γίνουν μέλη ΚΕΑΝΙΤΑ του KEANITA kids club, παρακαλείστε όπως διαβάσετε προσεκτικά αυτούς τους όρους και κανονισμούς, οι οποίοι διέπουν τη σχέση μεταξύ του ΚΕΑΝΙΤΑ kids club και εσάς, τον γονιό/κηδεμόνα των μελών του. Σε περίπτωση που διαφωνείτε με τους παρόντες όρους και κανονισμούς ή οποιοδήποτε μέρος αυτών, τότε συστήνεται να μην εγγράψετε τα παιδιά σας ως μέλη του ΚΕΑΝΙΤΑ kids club.

## Εγγραφή Μέλους

Για να γίνουν τα παιδιά σας μέλη του ΚΕΑΝΙΤΑ kids club, πρέπει να είστε γονιός ή κηδεμόνας άνω των 18 ετών και να έχετε παιδί ή παιδιά ηλικίας όχι μεγαλύτερη των 11 ετών. Εσείς, ο γονιός ή κηδεμόνας, θα αποστείλετε στο ΚΕΑΝΙΤΑ kids club τα απαιτούμενα στοιχεία, τα δικά σας και του παιδιού ή των παιδιών σας. Δικαίωμα εγγραφής έχουν τα παιδιά που είναι κάτω των 11 ετών και μόνιμοι κάτοικοι της Κύπρου.

Με την αποστολή των στοιχείων σας, υποδηλώνετε ότι συμφωνείτε να δεσμεύεστε από τους παρόντες όρους και κανονισμούς.

Στη συνέχεια, εφόσον γίνει αποδεχτεί η αίτησή σας, θα έχετε πρόσβαση στην ψηφιακή ΚΕΑΝΙΤΟ-κάρτα μέλους, πάνω στην οποία αναγράφεται ο ξεχωριστός αριθμός μέλους του παιδιού.

## Κάρτα Μέλους ΚΕΑΝΙΤΑ

Τα μέλη, που κατέχουν την κάρτα μέλους ΚΕΑΝΙΤΑ, θα λαμβάνουν ταχυδρομικώς, μέσω μηνύματος SMS, μέσω email και/ή μέσω ενημέρωσης από το application ΚΕΑΝΙΤA (notifications):

- στοιχεία για να λαμβάνουν μέρος σε διαγωνισμούς
- στοιχεία για εκδηλώσεις
- δώρα
- στοιχεία σχετικά με εκπτώσεις που προσφέρονται από διάφορα καταστήματα με την παρουσίαση της ψηφιακής κάρτας μέλους ΚΕΑΝΙΤΑ
- σεμινάρια
- οποιοδήποτε άλλο προνόμιο επιθυμεί να προσφέρει το ΚΕΑΝΙΤΑ kids club στα μέλη του κάθε φορά

Τα μέλη θα έχουν επίσης την ευχέρεια να επικοινωνούν με το ΚΕΑΝΙΤΑ kids club.

## Η Οικογένεια της ΚΕΑΝ

Η KEAN SOFT DRINΚS LIMITED δύναται να χρησιμοποιήσει τα στοιχεία επικοινωνίας σας (του γονέα/κηδεμόνα) για να σας στέλνει υλικό για διαφημιστικούς σκοπούς και για την προώθηση των προϊόντων, δραστηριοτήτων και εκδηλώσεων της ΚΕΑΝ SOFT DRINΚS LIMITED, που είναι πιθανό να σας ενδιαφέρουν.

## Παροχή Πληροφοριών

Αναγνωρίζετε ότι τα στοιχεία που δίνετε και τα έργα που δύναται να αποστέλλετε εσείς ή τα παιδιά σας από καιρό σε καιρό είναι με τη δική σας αποκλειστική ευθύνη. Δεν ευθύνεται ούτε εγγυάται το ΚΕΑΝΙΤΑ kids club την ακρίβεια, ορθότητα, σαφήνεια, πληρότητα, ακεραιότητα ή αυθεντικότητα οποιωνδήποτε στοιχείων ή οποιουδήποτε έργου ή επικοινωνίας που έχει λάβει από εσάς ή και τα παιδιά σας.

Επίσης είναι ευθύνη σας να ενημερώνετε το ΚΕΑΝΙΤΑ kids club για οποιαδήποτε αλλαγή των στοιχείων σας και των στοιχείων των παιδιών σας. Σε περίπτωση αλλαγής στοιχείων για την οποία δεν έχει ενημερωθεί η εταιρεία, η εταιρεία έχει το δικαίωμα διαγραφής οποιουδήποτε μέλους. Σε περίπτωση που διαπιστώσει η εταιρεία αναληθή ή ψευδή στοιχεία, τότε διατηρεί το δικαίωμα να διαγράψει ή να μην κάνει αποδεκτή την αίτηση κάποιου μέλους. Στην περίπτωση που το Μέλος έχει λάθος στοιχεία και δεν μπορεί η εταιρεία να επικοινωνήσει μαζί του, θα υπάρξει διαγραφή των στοιχείων του.

## Ενημέρωση και αποποίηση ευθύνης

Οι πληροφορίες και τα λοιπά στοιχεία που διατίθενται στο application και στα έντυπα που ανεβαίνουν σε αυτό, και αφορούν για παράδειγμα θέματα κοινωνικά, περιβαλλοντικά, υγιεινής ζωής και διατροφής, συλλέγονται από το ΚΕΑΝΙΤΑ kids club από προσιτές στο κοινό πηγές και παρέχονται προς εσάς και τα παιδιά σας αποκλειστικά και μόνο για ενημερωτικούς και εκπαιδευτικούς σκοπούς. Το ΚΕΑΝΙΤΑ kids club καταβάλλει κάθε προσπάθεια για να διασφαλίσει ότι οι πληροφορίες που περιέχονται στο application και στα έντυπα είναι ακριβείς, αλλά δεν αναλαμβάνει καμία ευθύνη ή υποχρέωση για οποιαδήποτε λάθη, παραλείψεις ή ανακρίβειες περιεχομένου.

Περαιτέρω, το ΚΕΑΝΙΤΑ kids club δεν παρέχει υποσχέσεις σχετικά με τα αποτελέσματα που λαμβάνονται από τη χρήση του application και των εντύπων, των πληροφοριών και του περιεχομένου και των προσφορών, των προϊόντων και των υπηρεσιών που προσφέρονται στα μέλη, τα οποία παρέχονται «ως έχουν». Προτρέπονται οι γονείς και/ή κηδεμόνες των μελών του ΚΕΑΝΙΤΑ kids club πάντα να συμβουλεύονται πρώτα ειδικούς και εμπειρογνώμονες για οποιοδήποτε θέμα αφορά τη σωματική ή ψυχική υγεία των παιδιών τους.

## Επικοινωνίες με το ΚΕΑΝΙΤΑ kids club

Όλες οι επικοινωνίες μεταξύ των παιδιών σας και του ΚΕΑΝΙΤΑ kids club θα είναι εμπιστευτικές και θα χειρίζονται από το ΚΕΑΝΙΤΑ kids club από επαγγελματίες που έχουν τύχει ειδικής εκπαίδευσης σχετικά με τον τρόπο επικοινωνίας με παιδιά, και οι οποίοι θα εποπτεύονται από κατάλληλα στελέχη.

## Παύση Μέλους και Διαγραφή

Μόλις ένα μέλος κλείσει τα 11 έτη ηλικίας, δεν θα θεωρείται πλέον μέλος του ΚΕΑΝΙΤΑ kids club και δεν θα μπορεί να επωφεληθεί από τα προνόμια των κατόχων Κάρτας Μέλους ΚΕΑΝΙΤΑ.

Εάν σε οποιοδήποτε χρόνο επιθυμείτε να διαγραφούν τα στοιχεία σας, μπορείτε ανά πάσα στιγμή να επικοινωνήσετε με το ΚΕΑΝΙΤΑ kids club μέσω μηνύματος ηλεκτρονικού ταχυδρομείου στη διεύθυνση keanita@keanltd.com.cy, με θέμα «Διαγραφή Στοιχείων Μέλους ΚΕΑΝΙΤΑ kids club», και το όνομα και επίθετο των μελών που επιθυμείτε να διαγραφούν.

Επιπλέον, μπορείτε να ζητήσετε διαγραφή των στοιχείων μέσα από το application και την επιλογή «Delete Account».

Συμφωνείτε όπως, εάν δεν ζητήσετε διαγραφή των στοιχείων σας όπως πιο πάνω, τότε, μετά την παύση σας ως Μέλος, τα στοιχεία σας διαγράφονται από το σύστημα εντός 3 μηνών μετά από την αποφοίτησή τους.

Σε αυτή την περίπτωση, εάν επιθυμείτε να διαγραφούν τα στοιχεία σας, μπορείτε ανά πάσα στιγμή να επικοινωνήσετε με την KEAN SOFT DRINΚS LIMITED μέσω μηνύματος ηλεκτρονικού ταχυδρομείου στη διεύθυνση kean@keanltd.com.cy, με θέμα «Διαγραφή στοιχείων», και το όνομα και επίθετό σας. Η διαγραφή των στοιχείων σας από το σύστημα θα γίνει εντός διαστήματος 3 μηνών μετά την αποφοίτησή τους.

## Δικαιώματα Πνευματικής Ιδιοκτησίας

Το ΚΕΑΝΙΤΑ kids club, το περιεχόμενο του application (προγράμματα, κείμενο, πληροφοριακό υλικό κάθε μορφής, δεδομένα, λογισμικό, γραφικά, σχέδια, εικονίδια, εικόνες, εμπορικά σήματα, επωνυμίες, λογότυπα, κλπ.) αποτελούν ιδιοκτησία της KEAN SOFT DRINΚS LIMITED, η οποία προστατεύεται από τους νόμους της Κυπριακής Δημοκρατίας. Απαγορεύεται οποιαδήποτε τροποποίηση, δημοσίευση, μετάδοση, μεταβίβαση, αναπαραγωγή, διανομή, παρουσίαση, σύνδεση, φόρτωση (download) ή με άλλο τρόπο εκμετάλλευση, εν όλο ή εν μέρει, του περιεχομένου του application με οποιονδήποτε τρόπο ή μέσο για οποιοδήποτε σκοπό.

## Υποβολή Ιδεών και Εισηγήσεων

Εάν έχετε ιδέες και εισηγήσεις σχετικά με το application ή τις προσφορές ή τις δραστηριότητες του ΚΕΑΝΙΤΑ kids club, θα θέλαμε να τις ακούσουμε, όμως σε καμία περίπτωση η αποκάλυψη ιδέας ή εισήγησης που υποβάλλεται θα υπόκειται σε οποιαδήποτε υποχρέωση εμπιστευτικότητας ή προσδοκίας για αποζημίωση. Υποβάλλοντας την ιδέα ή την εισήγηση παραιτείστε παντός δικαιώματος όσον αφορά την ιδέα ή την εισήγηση.

## Λειτουργία του application

Το διαδίκτυο δεν είναι ασφαλές περιβάλλον και, ενώ το ΚΕΑΝΙΤΑ kids club χρησιμοποιεί λογισμικό κατά των ιών ηλεκτρονικών υπολογιστών, δεν εγγυάται ότι οι λειτουργίες του application θα είναι αδιάλειπτες ή απαλλαγμένες από κάθε είδους σφάλματα και ιούς και δεν ευθύνεται για οποιαδήποτε απώλεια δεδομένων ή διακοπή ή παύση μετάδοσης ή άλλη ζημιά οφειλόμενη είτε σε χρήση, αντιγραφή, φόρτωση (download) είτε σε αλλοίωση ή μόλυνση με ιούς ή άλλες μη επιτρεπόμενες και/ή κακόβουλες παρεμβάσεις τρίτων σε αρχεία και πληροφορίες που διατίθενται μέσω του application. Ο χρήστης είναι αποκλειστικά υπεύθυνος για την προστασία του συστήματός του από ιούς.

## Τροποποίηση Όρων και Κανονισμών

Το ΚΕΑΝΙΤΑ kids club δύναται, από καιρό σε καιρό, να αλλάξει, τροποποιήσει, προσθέσει ή αφαιρέσει εν όλο ή εν μέρει τους παρόντες όρους και κανονισμούς και το περιεχόμενο του application κατά την απόλυτη διακριτική του ευχέρεια. Οι τροποποιήσεις αυτές τίθενται σε εφαρμογή με τη σχετική ειδοποίηση που τοποθετείται στο application. Παρακαλείστε να ελέγχετε τακτικά τους όρους και κανονισμούς και την πολιτική προστασίας προσωπικών δεδομένων για τυχόν ενημερώσεις. Εν πάση περιπτώσει, εφόσον εξακολουθείτε να έχετε παιδιά μέλη, τεκμαίρεται ότι έχετε αποδεχθεί τις οποιεσδήποτε αλλαγές.

## Τερματισμός

Το application, οι υπηρεσίες και τα προϊόντα ΚΕΑΝΙΤΑ kids club προσφέρονται με την πρωτοβουλία και διακριτική ευχέρεια της KEAN SOFT DRINΚS LIMITED προς εσάς και τα παιδιά σας, χωρίς αντάλλαγμα. Το ΚΕΑΝΙΤΑ kids club δύναται να διακόψει για οποιοδήποτε χρονικό διάστημα ή και να τερματίσει τη λειτουργία του καθώς και τη λειτουργία του application KEANITA οποτεδήποτε και χωρίς ειδοποίηση.

## Επικοινωνία

Μπορείτε να επικοινωνήσετε με το ΚΕΑΝΙΤΑ kids club για οποιοδήποτε θέμα:

- Τηλέφωνο: 80007090
- Αρ. Τηλεομοιότυπου: 25324289
- Ηλεκτρονική Διεύθυνση: keanita@keanltd.com.cy
- Διεύθυνση: Λεωφόρος Προμάχων Ελευθερίας, αρ. 35, Άγιος Αθανάσιος, Τ.Κ. 4103, Λεμεσός, Κύπρος

Το ΚΕΑΝΙΤΑ kids club είναι παράρτημα της KEAN SOFT DRINΚS LIMITED, εταιρεία εγγεγραμμένη στον Έφορο Εταιρειών με αριθμό εγγραφής ΗΕ 628 και εγγεγραμμένο γραφείο στη Λεωφόρο Προμάχων Ελευθερίας, αρ. 35, Άγιος Αθανάσιος, Τ.Κ. 4103, Λεμεσός, Κύπρος.

# Πολιτική Προστασίας Προσωπικών Δεδομένων

Το ΚΕΑΝΙΤΑ kids club συλλέγει δεδομένα δικά σας και των παιδιών σας, εφ’ όσον τα παιδιά είναι μέλη του ΚΕΑΝΙΤΑ kids club, και τηρεί αρχείο αυτών. Το ΚΕΑΝΙΤΑ kids club έχει πρόσβαση στο αρχείο αυτό και επεξεργάζεται τα προσωπικά και μη προσωπικά δεδομένα σας σύμφωνα με την παρούσα πολιτική του.

Με την εγγραφή σας, παρέχετε τη συγκατάθεσή σας για τη συλλογή, φύλαξη και επεξεργασία των προσωπικών δεδομένων σας και αυτών των παιδιών σας, είτε αυτή η συγκατάθεση είναι ρητή για σκοπούς επικοινωνίας, είτε αυτή τεκμαίρεται ότι υφίσταται διά της εγγραφής ως μέλος του ΚΕΑΝΙΤΑ kids club.

## Συλλογή Δεδομένων

Τα προσωπικά δεδομένα που συλλέγονται για το ΚΕΑΝΙΤΑ kids club είναι στοιχεία ταυτοποίησης (όνομα, ηλικία, ημερομηνία γέννησης, φύλο) και επικοινωνίας (ταχυδρομική διεύθυνση, τηλέφωνο, μέσο διαδικτύου). Αυτά τα δεδομένα συλλέγονται κατά την εγγραφή του μέλους. Επίσης, το ΚΕΑΝΙΤΑ kids club πιθανόν να κρατήσει αρχείο επικοινωνίας ή αλληλογραφίας, δικής σας και των παιδιών σας.

## Χρήση Δεδομένων

Η επεξεργασία των δεδομένων εκ μέρους του ΚΕΑΝΙΤΑ kids club θα λαμβάνει χώρα για λόγους επικοινωνίας, στατιστικούς σκοπούς, καθώς και για λόγους βελτίωσης των παρεχόμενων υπηρεσιών του.

Το ΚΕΑΝΙΤΑ kids club δυνατό να μεταβιβάζει τα προσωπικά δεδομένα σας στην KEAN SOFT DRINΚS LIMITED ή σε οποιοδήποτε παράρτημα αυτής, για σκοπούς αποστολής διαφημιστικού και προωθητικού υλικού.

## Αποκάλυψη Δεδομένων

Το ΚΕΑΝΙΤΑ kids club ουδέποτε γνωστοποιεί, μεταβιβάζει ή αποκαλύπτει τα προσωπικά δεδομένα αυθαίρετα σε τρίτους, εκτός εάν:

- έχετε δώσει τη ρητή σας συγκατάθεση για αποκάλυψη των προσωπικών σας δεδομένων για καθορισμένο σκοπό, είτε στους Όρους και Κανονισμούς ή άλλως πως,
- η αποκάλυψη γίνεται στην KEAN SOFT DRINΚS LIMITED ή σε συνδεδεμένη εταιρεία,
- η αποκάλυψη απαιτείται από τον νόμο ή δικαστικό διάταγμα.

## Ασφάλεια Δεδομένων

Το ΚΕΑΝΙΤΑ kids club συνεργάζεται με επαγγελματική εταιρεία η οποία παρέχει τον σέρβερ πάνω στον οποίο βρίσκεται το application και η βάση δεδομένων με τα προσωπικά δεδομένα σας, η οποία διατηρεί δική της αυστηρή πολιτική προστασίας δεδομένων όσον αφορά τη διαβίβαση των δεδομένων σας στους σέρβερ της και τη φύλαξή τους εκεί.

Το application είναι προστατευμένο με SSL και ενημερωμένα αντιικά προγράμματα και firewall.

Το ΚΕΑΝΙΤΑ kids club θα λαμβάνει κάθε απαραίτητο τεχνικό, συμβατικό, διοικητικό μέτρο και μέτρο φυσικής ασφάλειας προκειμένου να διαφυλάξει την τήρηση του απορρήτου των προσωπικών σας δεδομένων. Δίνονται επίσης οδηγίες στους υπαλλήλους οι οποίοι έχουν πρόσβαση στα προσωπικά σας δεδομένα, όπως αυτά χρησιμοποιηθούν μόνο για τον σκοπό για τον οποίο συλλέγονται και επεξεργάζονται.

## Πρόσβαση και Τροποποίηση Δεδομένων

Έχετε δικαίωμα πρόσβασης στα προσωπικά σας δεδομένα και τα προσωπικά δεδομένα των παιδιών σας. Περαιτέρω, έχετε το δικαίωμα διόρθωσης, αλλαγής και/ή διαγραφής των προσωπικών αυτών δεδομένων. Μπορείτε να τροποποιήσετε τα προσωπικά σας στοιχεία μέσω του application και της επιλογής «Profile > Edit Profile».

Η διαχείριση και προστασία των δεδομένων σας υπόκεινται πάντα στον περί Επεξεργασίας Δεδομένων Προσωπικού Χαρακτήρα (Προστασία του Ατόμου) Νόμο, όπως αυτός δύναται να τροποποιηθεί ή αντικατασταθεί από καιρό σε καιρό.

## Επικοινωνία

Μπορείτε να επικοινωνήσετε με το ΚΕΑΝΙΤΑ kids club:

- Θέση: Υπεύθυνος Επεξεργασίας Δεδομένων
- Τηλέφωνο: 80007090
- Αρ. Τηλεομοιότυπου: 25324289
- Ηλεκτρονική Διεύθυνση: keanita@keanltd.com.cy
- Διεύθυνση: Λεωφόρος Προμάχων Ελευθερίας, αρ. 35, Άγιος Αθανάσιος, Τ.Κ. 4103, Λεμεσός, Κύπρος') on conflict (slug) do nothing;
insert into pages (slug, title, body_md) values ('about', 'Η ιστορία μας', '') on conflict (slug) do nothing;
insert into pages (slug, title, body_md) values ('privacy', 'Πολιτική Απορρήτου', '') on conflict (slug) do nothing;
