// Generates supabase/seed.sql from the RN app's mock data (../nextjs-sample/data/mock).
// Run: node scripts/gen-seed.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const MOCK = resolve(import.meta.dirname, '../../nextjs-sample/data/mock');
const read = (f) => readFileSync(resolve(MOCK, f), 'utf8');
const q = (v) => v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const arr = (a) => `array[${a.map(q).join(',')}]::text[]`;
const js = (v) => q(JSON.stringify(v));

// Evaluate a TS mock file by stripping types/imports and requires.
function load(file, exportName) {
  let src = read(file)
    .replace(/^import[^\n]*\n/gm, '')
    .replace(/export (interface|type) [\s\S]*?\n}\n/g, '')
    .replace(/export type [^\n]*\n/g, '')
    .replace(/require\(([^)]*)\)/g, (_, p) => p)           // keep the asset path string
    .replace(/: ImageSourcePropType/g, '')
    .replace(/(: )?(Record<[^=]*>|[A-Za-z]+\[\])( =)/g, '$3')
    .replace(/export const/g, 'const');
  src += `\n;return ${exportName};`;
  return new Function(src)();
}

const products = load('products.ts', 'products');
const characters = load('characters.ts', 'characters');
const events = load('events.ts', 'events');
const gifts = load('gifts.ts', 'gifts');
const sliders = load('home-sliders.ts', 'homeSliders');
const kc = load('kids-club.ts', '{storeCategories, partnerStores}');
const { onlinePuzzles, downloadActivities } = load('activities.ts', '{onlinePuzzles, downloadActivities}');

const out = [];
out.push('-- AUTO-GENERATED by scripts/gen-seed.mjs from nextjs-sample/data/mock. Safe to re-run (idempotent where keyed).');

// store categories
out.push('\n-- store categories');
for (const [id, name] of Object.entries(kc.storeCategories))
  out.push(`insert into store_categories (id, name, old_import_id) values (${id}, ${q(name)}, ${id}) on conflict (id) do update set name = excluded.name;`);
out.push(`select setval('store_categories_id_seq', (select max(id) from store_categories));`);

// stores + discounts
out.push('\n-- partner stores');
for (const s of kc.partnerStores) {
  out.push(`with s as (insert into stores (name, category_id, phone, website, description, logo_url, old_import_id) values (${q(s.name)}, ${s.categoryId}, ${q(s.phone)}, ${q(s.website)}, ${q(s.description)}, ${s.logo ? q(`stores/store-${s.id}.jpg`) : 'null'}, ${s.id}) returning id)
insert into store_discounts (store_id, value, description) select s.id, d.v, d.d from s, (values ${s.discounts.map((d) => `(${d.value}, ${q(d.description)})`).join(',')}) as d(v, d);`);
}

// products
out.push('\n-- products');
products.forEach((p, i) => out.push(`insert into products (name, category, tagline, description, image_url, accent_color, bg_color, serving_size, highlights, ingredients, nutrition, sort_order, old_import_id) values (${q(p.name)}, ${q(p.category)}, ${q(p.tagline)}, ${q(p.description)}, ${q('products/' + p.image.split('/').pop())}, ${q(p.accentColor)}, ${q(p.bgColor)}, ${q(p.servingSize)}, ${arr(p.highlights)}, ${arr(p.ingredients)}, ${js(p.nutrition)}, ${i}, ${p.id});`));

// characters
out.push('\n-- characters');
characters.forEach((c, i) => out.push(`insert into characters (id, slug, name, tagline, description, best_friend, power, favorite_juice, image_url, accent_color, bg_color, sort_order) values (${c.id}, ${q(c.slug)}, ${q(c.name)}, ${q(c.tagline)}, ${q(c.description)}, ${q(c.bestFriend)}, ${q(c.power)}, ${q(c.favoriteJuice)}, ${q('characters/' + c.image.split('/').pop())}, ${q(c.accentColor)}, ${q(c.bgColor)}, ${i}) on conflict (slug) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description;`));
out.push(`select setval('characters_id_seq', (select max(id) from characters));`);

// events
out.push('\n-- events (sample, published)');
events.forEach((e, i) => out.push(`insert into events (type, title, description, date, time_label, location, image_url, accent_color, bg_color, status, sort_order, old_import_id) values (${q(e.type)}, ${q(e.title)}, ${q(e.description)}, ${q(e.date)}, ${q(e.time)}, ${q(e.location)}, ${q('events/' + e.image.split('/').pop())}, ${q(e.accentColor)}, ${q(e.bgColor)}, 'published', ${i}, ${e.id});`));

// sliders
out.push('\n-- home sliders');
sliders.forEach((s, i) => out.push(`insert into home_sliders (title, subtitle, image_url, accent_color, bg_color, sort_order) values (${q(s.title)}, ${q(s.subtitle)}, ${q('sliders/' + s.image.split('/').pop())}, ${q(s.accentColor)}, ${q(s.bgColor)}, ${i});`));

// activities
out.push('\n-- activities');
onlinePuzzles.forEach((a, i) => out.push(`insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('puzzle', ${q(a.title)}, 'Χρωμοσελίδες', ${q('activities/' + a.image.split('/').pop())}, ${q(a.pdfUrl)}, ${i}, ${a.id});`));
downloadActivities.forEach((a, i) => out.push(`insert into activities (kind, title, category, image_url, file_url, sort_order, old_import_id) values ('download', ${q(a.title)}, ${q(a.category)}, ${q('activities/' + a.image.split('/').pop())}, ${q(a.pdfUrl)}, ${i}, ${a.id});`));

// gifts
out.push('\n-- gifts');
gifts.forEach((g, i) => out.push(`insert into gifts (name, description, cost, category, emoji, color, bg_color, stock, requires_approval, sort_order) values (${q(g.name)}, ${q(g.description)}, ${g.cost}, ${q(g.category)}, ${q(g.emoji)}, ${q(g.color)}, ${q(g.bg)}, ${g.inStock ? 'null' : 0}, ${g.requiresApproval}, ${i});`));

// reward rules (from rewards.tsx copy: game ≤150/day, login 5, event ≤250, qr 20)
out.push('\n-- reward rules');
const rules = [
  ['daily_login', 'Ημερήσια σύνδεση', 5, null, {}],
  ['streak_bonus', 'Μπόνους σερί', 10, null, { tiers: { 3: 10, 7: 30, 30: 100 } }],
  ['game', 'Φρουτοτρέλα (ανά φρούτο)', 1, 150, { completion_bonus: 5 }],
  ['event_rsvp', 'Δήλωση συμμετοχής σε εκδήλωση', 10, null, {}],
  ['profile_complete', 'Συμπλήρωση προφίλ', 50, null, {}],
  ['qr_scan', 'Σκανάρισμα QR προϊόντος', 20, null, {}],
  ['birthday', 'Δώρο γενεθλίων', 50, null, {}],
  ['gift_redeem', 'Εξαργύρωση δώρου', 0, null, {}],
  ['refund', 'Επιστροφή πόντων', 0, null, {}],
  ['manual', 'Χειροκίνητη προσαρμογή', 0, null, {}],
  ['expiry', 'Λήξη πόντων', 0, null, {}],
];
for (const [k, l, p, cap, cfg] of rules)
  out.push(`insert into reward_rules (key, label, points, daily_cap, config) values (${q(k)}, ${q(l)}, ${p}, ${cap ?? 'null'}, ${js(cfg)}) on conflict (key) do nothing;`);

// settings (from contact.tsx, emergency button, rewards footnote, old global_settings)
out.push('\n-- app settings');
const settings = {
  contact_email: ['keanita@keanltd.com.cy', 'Email επικοινωνίας'],
  contact_phone: ['80007090', 'Τηλέφωνο επικοινωνίας'],
  contact_address: ['Τ.Θ. 50300, 3603, Λεμεσός', 'Διεύθυνση'],
  contact_hours: ['Δευ–Πέμ 10:00–13:00 & 14:00–16:00, Παρ 10:00–13:30', 'Ώρες λειτουργίας'],
  emergency_phone: ['80007090', 'Αριθμός κουμπιού έκτακτης ανάγκης (αρχική οθόνη)'],
  social_facebook: ['https://www.facebook.com/keanita', 'Facebook'],
  social_instagram: ['https://www.instagram.com/keanitaofficial/', 'Instagram'],
  social_youtube: ['https://www.youtube.com/user/keansoftdrinks', 'YouTube'],
  kid_max_age: [11, 'Ηλικία λήξης μέλους Kids Club'],
  kid_auto_approve: [false, 'Αυτόματη έγκριση παιδιών'],
  points_expiry_months: [12, 'Μήνες μέχρι τη λήξη πόντων'],
  birthday_push_enabled: [true, 'Αποστολή ευχών γενεθλίων'],
  birthday_message: ['Χρόνια πολλά {name}! 🎂 Η Keanita σου εύχεται μια υπέροχη μέρα γεμάτη χυμό και χαμόγελα!', 'Μήνυμα γενεθλίων ({name} = όνομα παιδιού)'],
  birthday_points: [50, 'KP δώρο γενεθλίων'],
  birthday_video_url: [null, 'Βίντεο γενεθλίων'],
  intro_video_url: [null, 'Εισαγωγικό βίντεο'],
  event_reminder_days: [2, 'Ημέρες πριν την εκδήλωση για υπενθύμιση'],
  membership_tier_label: ['Χρυσό μέλος', 'Ετικέτα επιπέδου μέλους (προφίλ)'],
  home_product_chips: [[{ emoji: '🍊', label: '20% φυσικός χυμός' }, { emoji: '✨', label: 'Έξτρα βιταμίνη C' }, { emoji: '🌿', label: 'Χωρίς πρόσθετα' }], 'Chips προϊόντων στην αρχική'],
  home_quick_actions: [['rewards', 'gifts', 'discounts', 'products', 'activities', 'about'], 'Ενεργά κουμπιά γρήγορης πρόσβασης'],
  min_app_version: ['1.0.0', 'Ελάχιστη έκδοση εφαρμογής (force update)'],
  maintenance_mode: [false, 'Λειτουργία συντήρησης'],
};
for (const [k, [v, d]] of Object.entries(settings))
  out.push(`insert into app_settings (key, value, description) values (${q(k)}, ${js(v)}::jsonb, ${q(d)}) on conflict (key) do nothing;`);

// pages
out.push('\n-- pages');
const termsGroups = load('../terms.ts', 'termsGroups');
const terms = termsGroups.map((g) => `# ${g.heading}\n\n` + g.sections.map((sec) =>
  (sec.title ? `## ${sec.title}\n\n` : '') + (sec.paragraphs ?? []).join('\n\n') + (sec.bullets?.length ? '\n\n' + sec.bullets.map((b) => `- ${b}`).join('\n') : '')
).join('\n\n')).join('\n\n');
out.push(`insert into pages (slug, title, body_md) values ('terms', 'Όροι & Κανονισμοί', ${q(terms)}) on conflict (slug) do nothing;`);
out.push(`insert into pages (slug, title, body_md) values ('about', 'Η ιστορία μας', '') on conflict (slug) do nothing;`);
out.push(`insert into pages (slug, title, body_md) values ('privacy', 'Πολιτική Απορρήτου', '') on conflict (slug) do nothing;`);

writeFileSync(resolve(import.meta.dirname, '../supabase/seed.sql'), out.join('\n') + '\n');
console.log(`seed.sql: ${products.length} products, ${characters.length} characters, ${events.length} events, ${kc.partnerStores.length} stores, ${onlinePuzzles.length + downloadActivities.length} activities, ${gifts.length} gifts, ${Object.keys(settings).length} settings`);
